/**
 * The <code>jason.compiler</code> package currently contains of two classes:
 * {@link jason.compiler.JasonProcessor} and {@link jason.compiler.Merge}.
 * The Jason compiler is invoked directly  by javac.
 * The syntax to invoke javac is:
 * <pre>
 *	<code>javac -processor jason.compiler.JasonProcessor -cp ... &lt;src_files&gt;</code>
 * </pre>
 * Once a standalone policy file is generated it can be merged with the WSDL
 * file generated by <code>wsgen</code> by the {@link jason.compiler.Merge merger}.
 */
package jason.compiler;

